[tool.poetry]
name = "maddeb"
version = "0.0.1"
description = "Galaxy deblender from variational autoencoders"
authors = ["Biswajit Biswas <biswas@apc.in2p3.fr>"]
readme = "README.md"
include = ["maddeb/data/*"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "*"
pandas = "*"
tensorflow = "*"
tensorflow-probability = "*"
scikit-image = "*"
sep = "*"
galcheat = "*"
simulations = {version = "*", optional=true}
matplotlib = {version = "*", optional=true}
seaborn = {version = "*", optional=true}
galsim = {version = "*", optional=true}
pytest = {version="*", optional=true}
precommit = {version="*", optional=true} 
blending_toolkit = {git="https://github.com/b-biswas/BlendingToolKit", branch = "madness-branch", optional=true }
jupyter = {version="*", optional=true}
ipykernel = {version="*", optional=true}
tensorflow-datasets = {version="*", optional=true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
sims = ["simulations", "blending_toolkit", "tensorflow-datasets", "matplotlib", "galsim", "seaborn"]
notebooks = ["jupyter", "ipykernel"]
dev = ["jupyter", "ipykernel", "matplotlib", "galsim", "seaborn", "pytest", "pre-commit"]

