TF_DATASET_PATH: "/sps/lsst/users/bbiswas/simulations/CATSIM_tfDataset/"
TEST_DATA_LOAD_PATH: "/sps/lsst/users/bbiswas/simulations/CATSIM_tfDataset/"
RESULTS_SAVE: "/sps/lsst/users/bbiswas/MADNESS_results/"